/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import static java.awt.geom.Point2D.distance;
import java.time.Duration;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.CarFleet;
import model.Cars;
/**
 *
 * @author balumullamuri
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    CarFleet carfleet;
    public CreateJPanel(CarFleet carfleet) {
        initComponents();
        this.carfleet = carfleet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        mf = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mftxt = new javax.swing.JTextField();
        serialtxt = new javax.swing.JTextField();
        model_txt = new javax.swing.JTextField();
        yeartxt = new javax.swing.JTextField();
        locationtxt = new javax.swing.JTextField();
        emctxt = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        seatstxt = new javax.swing.JTextField();
        yesrbtn = new javax.swing.JRadioButton();
        norbtn = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        distancetxt = new javax.swing.JTextField();

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("UBER CARS");

        mf.setText("Manufacturer:");

        jLabel2.setText("Availability:");

        jLabel3.setText("Serial_number:");

        jLabel4.setText("Model_num:");

        jLabel5.setText("Year of manufacture:");

        jLabel6.setText("Location:");

        jLabel7.setText("Expired_Maintenance_Cert:");

        serialtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialtxtActionPerformed(evt);
            }
        });

        yeartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeartxtActionPerformed(evt);
            }
        });

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Seats:");

        btngroup.add(yesrbtn);
        yesrbtn.setText("Yes");
        yesrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesrbtnActionPerformed(evt);
            }
        });

        btngroup.add(norbtn);
        norbtn.setText("No");

        jLabel8.setText("Distance:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(mf)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(locationtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yeartxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatstxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(model_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serialtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yesrbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(norbtn)
                                .addGap(0, 40, Short.MAX_VALUE))
                            .addComponent(mftxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emctxt)
                            .addComponent(distancetxt))
                        .addGap(257, 257, 257)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(savebtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(title)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mf)
                    .addComponent(mftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yesrbtn)
                    .addComponent(norbtn))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(serialtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(model_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(seatstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(yeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(distancetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(savebtn)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serialtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialtxtActionPerformed

    private void yeartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yeartxtActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        yesrbtn.setActionCommand("Yes");
        norbtn.setActionCommand("No");
        String manufacturer = mftxt.getText();
        int year = Integer.parseInt(yeartxt.getText());
        int seats = Integer.parseInt(seatstxt.getText());
        String location = locationtxt.getText();
        String cert = emctxt.getText();
        double distance = Double.parseDouble(distancetxt.getText());
        String modelnum = model_txt.getText();
        long serialnum = Long.parseLong(serialtxt.getText());
        String availability = btngroup.getSelection().getActionCommand();
        

              
        String reg="^[a-zA-Z]{3,}$";  //manufacturer
        Pattern prat=Pattern.compile(reg);
        Matcher match=prat.matcher(mftxt.getText());
        boolean set=match.find();
        if(set==false)
        {
            mftxt.setBackground(Color.red);
         }
        else
        {
            mftxt.setBackground(Color.green);
                 }
        
        String rege="^[A-Z]{2,}[0-9]{3}$";      //model number
        Pattern pratr=Pattern.compile(rege);
        Matcher matche=pratr.matcher(model_txt.getText());
        boolean sete=matche.find();
        if(set==false)
        {
            mftxt.setBackground(Color.red);
         }
        else
        {
            mftxt.setBackground(Color.green);
                 }
        String regex="^(19|20)\\\\d{2}$";       //manufactured year
        Pattern pratre=Pattern.compile(rege);
        Matcher matchea=pratre.matcher(yeartxt.getText());
        boolean setei=matchea.find();
        if(set==false)
        {
            mftxt.setBackground(Color.red);
         }
        else
        {
            mftxt.setBackground(Color.green);
                 }
        
        String regu="^[a-zA-Z]{3,}$";       //available location
        Pattern pratn=Pattern.compile(reg);
        Matcher matcho=pratn.matcher(locationtxt.getText());
        boolean setp=matcho.find();
        if(set==false)
        {
            mftxt.setBackground(Color.red);
         }
        else
        {
            mftxt.setBackground(Color.green);
                 }
        
        String regm="^[1-9]{1}$";
        Pattern prats=Pattern.compile(reg);
        Matcher matchs=prats.matcher(seatstxt.getText());
        boolean sets=matchs.find();
        if(set==false)
        {
            mftxt.setBackground(Color.red);
         }
        else
        {
            mftxt.setBackground(Color.green);
                 }
      
    
        Cars cf = carfleet.addNewCars();
        cf.setManufacturer(manufacturer);
        cf.setCert(cert);
        cf.setLocation(location);
        cf.setAvailability(availability);
        cf.setModelnum(modelnum);
        cf.setSeats(seats);
        cf.setYear(year);
        cf.setSerialnum(serialnum);
        cf.setDistance(distance);
        
        JOptionPane.showMessageDialog(this, "New cars added");
        
        mftxt.setText("");
        yeartxt.setText("");
        seatstxt.setText("");
        yesrbtn.setSelected(false);
        norbtn.setSelected(false);
        locationtxt.setText("");
        emctxt.setText("");
        model_txt.setText("");
        serialtxt.setText("");
        distancetxt.setText("");
        
        
    }//GEN-LAST:event_savebtnActionPerformed

    private void yesrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesrbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesrbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroup;
    private javax.swing.JTextField distancetxt;
    private javax.swing.JTextField emctxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField locationtxt;
    private javax.swing.JLabel mf;
    private javax.swing.JTextField mftxt;
    private javax.swing.JTextField model_txt;
    private javax.swing.JRadioButton norbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField seatstxt;
    private javax.swing.JTextField serialtxt;
    private javax.swing.JLabel title;
    private javax.swing.JTextField yeartxt;
    private javax.swing.JRadioButton yesrbtn;
    // End of variables declaration//GEN-END:variables
}
