/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.CarFleet;
import model.Cars; 

/**
 *
 * @author balumullamuri
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    CarFleet carfleet;
    public ViewJPanel(CarFleet carfleet) {
        initComponents();
        this.carfleet=carfleet;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        seatstxt = new javax.swing.JTextField();
        mftxt = new javax.swing.JTextField();
        yesrbtn = new javax.swing.JRadioButton();
        serialtxt = new javax.swing.JTextField();
        norbtn = new javax.swing.JRadioButton();
        model_txt = new javax.swing.JTextField();
        yeartxt = new javax.swing.JTextField();
        mf = new javax.swing.JLabel();
        locationtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emctxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        distancetxt = new javax.swing.JTextField();
        viewbtn = new javax.swing.JButton();
        searchtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Manufacturer", "ModelNo", "SerialNo", "Availability", "Seats", "Year of manufacture", "Distance", "ExpCert", "Location"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        addbtn.setText("IMPORT");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Expired_Maintenance_Cert:");

        mftxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mftxtActionPerformed(evt);
            }
        });

        btngroup.add(yesrbtn);
        yesrbtn.setText("Yes");
        yesrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesrbtnActionPerformed(evt);
            }
        });

        serialtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialtxtActionPerformed(evt);
            }
        });

        btngroup.add(norbtn);
        norbtn.setText("No");
        norbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norbtnActionPerformed(evt);
            }
        });

        model_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_txtActionPerformed(evt);
            }
        });

        yeartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeartxtActionPerformed(evt);
            }
        });

        mf.setText("Manufacturer:");

        jLabel2.setText("Availability:");

        emctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emctxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Serial_number:");

        jLabel4.setText("Model_num:");

        jLabel5.setText("Year of manufacture:");

        jLabel6.setText("Location:");

        jLabel1.setText("Seats:");

        jLabel8.setText("Distance:");

        distancetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distancetxtActionPerformed(evt);
            }
        });

        viewbtn.setText("VIEW");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        searchtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxtActionPerformed(evt);
            }
        });
        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchtxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtKeyReleased(evt);
            }
        });

        jLabel9.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196)
                .addComponent(viewbtn)
                .addGap(26, 26, 26)
                .addComponent(addbtn)
                .addGap(18, 18, 18)
                .addComponent(deletebtn)
                .addGap(31, 31, 31)
                .addComponent(updatebtn)
                .addGap(24, 24, 24))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yesrbtn)
                        .addGap(23, 23, 23)
                        .addComponent(norbtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emctxt)
                            .addComponent(distancetxt)
                            .addComponent(locationtxt)
                            .addComponent(yeartxt)
                            .addComponent(seatstxt)
                            .addComponent(model_txt)
                            .addComponent(serialtxt)
                            .addComponent(mftxt))
                        .addGap(122, 122, 122))))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(mf))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(deletebtn)
                    .addComponent(updatebtn)
                    .addComponent(viewbtn)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mf)
                    .addComponent(mftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yesrbtn)
                    .addComponent(norbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serialtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(model_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(yeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(distancetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serialtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialtxtActionPerformed

    private void yeartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yeartxtActionPerformed

    private void distancetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distancetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distancetxtActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        
        String filePath = "/Users/balumullamuri/Desktop/UBERRR.txt";
        File file = new File(filePath);
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setColumnIdentifiers(columnsName);
            
            Object[] tableLines = br.lines().toArray();
            
            for(int i=0; i<tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);
            
            
            }
        
        }catch(Exception ex){
        
            System.out.println(ex);
        
        }
        
        
        
    }//GEN-LAST:event_addbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        
        int selectedRowIndex = table.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"please select a row to delete");
            return;
        }
         DefaultTableModel model = (DefaultTableModel)  table.getModel();
         
         model.removeRow(selectedRowIndex);
         
        
        JOptionPane.showMessageDialog(this,"Cars deleted");
        
        
    }//GEN-LAST:event_deletebtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
         
        int selectedRowIndex = table.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"please select a row to view");
            return;
        }
         DefaultTableModel model = (DefaultTableModel)  table.getModel();
        String manufacturer = model.getValueAt(selectedRowIndex, 0).toString();
        String modelnum = model.getValueAt(selectedRowIndex, 1).toString();
        String serialnum = model.getValueAt(selectedRowIndex, 2).toString();
        String availability = model.getValueAt(selectedRowIndex, 3).toString();
            if(availability.equals("yes")){
                yesrbtn.setSelected(true);
            }
            else{
                norbtn.setSelected(false);}
            if(availability.equalsIgnoreCase("Yes")){
                yesrbtn.setSelected(true);
                norbtn.setSelected(false);
                    }
                else{
                yesrbtn.setSelected(false);
                norbtn.setSelected(true);
    }
        String seats = model.getValueAt(selectedRowIndex, 4).toString();
        String year = model.getValueAt(selectedRowIndex, 5).toString();
        String distance = model.getValueAt(selectedRowIndex, 6).toString();
        String expcert = model.getValueAt(selectedRowIndex, 7).toString();
        String location = model.getValueAt(selectedRowIndex, 8).toString();
         
        model.setValueAt(manufacturer, selectedRowIndex, 0);
        model.setValueAt(modelnum, selectedRowIndex, 1);
        model.setValueAt(serialnum, selectedRowIndex, 2);
       
        model.setValueAt(seats, selectedRowIndex, 4);
        model.setValueAt(year, selectedRowIndex, 5);
        model.setValueAt(distance, selectedRowIndex, 6);
        model.setValueAt(expcert, selectedRowIndex, 7);
        model.setValueAt(location, selectedRowIndex, 8);
        
         mftxt.setText(manufacturer);
         model_txt.setText(modelnum);
         serialtxt.setText(serialnum);
         seatstxt.setText(seats);
         if(yesrbtn.isSelected()==true){
         yesrbtn.setText(availability);}
         if(norbtn.isSelected()==true){
         norbtn.setText(availability);}
         
         yeartxt.setText(year);
         distancetxt.setText(distance);
         emctxt.setText(expcert);
         locationtxt.setText(location);
         
        
      
        
        
        
        
        
    }//GEN-LAST:event_viewbtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
       /*int selectedRow = table.getSelectedRow();
       DefaultTableModel model =  (DefaultTableModel)  table.getModel();
       mftxt.setText(model.getValueAt(selectedRow , 0).toString());
       model_txt.setText(model.getValueAt(selectedRow , 1).toString());
       serialtxt.setText(model.getValueAt(selectedRow , 2).toString());
       seatstxt.setText(model.getValueAt(selectedRow , 4).toString());
       yeartxt.setText(model.getValueAt(selectedRow , 5).toString());
       distancetxt.setText(model.getValueAt(selectedRow , 6).toString());
       emctxt.setText(model.getValueAt(selectedRow , 7).toString());
       locationtxt.setText(model.getValueAt(selectedRow , 8).toString());*/
        
    }//GEN-LAST:event_tableMouseClicked

    private void model_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model_txtActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
       int i =table.getSelectedRow();
       DefaultTableModel model =  (DefaultTableModel)  table.getModel();
       if(i>=0){
           model.setValueAt(mftxt.getText(),i,0);
           model.setValueAt(model_txt.getText(),i,1);
           model.setValueAt(serialtxt.getText(),i,2);
           model.setValueAt(seatstxt.getText(),i,4);
           model.setValueAt(yeartxt.getText(),i,5);
           model.setValueAt(distancetxt.getText(),i,6);
           model.setValueAt(emctxt.getText(),i,7);
           model.setValueAt(locationtxt.getText(),i,8);
           
       
       }else{
           JOptionPane.showMessageDialog(null,"ERROR");
       
       
       }
        
    }//GEN-LAST:event_updatebtnActionPerformed

    private void yesrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesrbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesrbtnActionPerformed

    private void norbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_norbtnActionPerformed

    private void mftxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mftxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mftxtActionPerformed

    private void emctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emctxtActionPerformed

    private void searchtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxtActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_searchtxtActionPerformed

    private void searchtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model =  (DefaultTableModel)  table.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (model);
        table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchtxt.getText().trim()));
        
        
    }//GEN-LAST:event_searchtxtKeyPressed

    private void searchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model =  (DefaultTableModel)  table.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (model);
        table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchtxt.getText().trim()));
    }//GEN-LAST:event_searchtxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    public javax.swing.ButtonGroup btngroup;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField distancetxt;
    private javax.swing.JTextField emctxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationtxt;
    private javax.swing.JLabel mf;
    private javax.swing.JTextField mftxt;
    private javax.swing.JTextField model_txt;
    private javax.swing.JRadioButton norbtn;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTextField seatstxt;
    private javax.swing.JTextField serialtxt;
    private javax.swing.JTable table;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton viewbtn;
    private javax.swing.JTextField yeartxt;
    private javax.swing.JRadioButton yesrbtn;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
       DefaultTableModel model = (DefaultTableModel)  table.getModel();
       model.setRowCount(0);
       
       for(Cars cf: carfleet.getCarfleet()){ //for each value in carfleet arraylist
           Object[] row = new Object[9];     //array with 9 values
           row[0] = cf.getManufacturer();
           row[1] = cf.getModelnum();
           row[2] = cf.getSerialnum();
           row[3] = cf.getAvailability();
           row[4] = cf.getSeats();
           row[5] = cf.getYear();
           row[6] = cf.getDistance();
           row[7] = cf.getCert();
           row[8] = cf.getLocation();
           
           model.addRow(row);
       
       }
    }
 
}
